"""Deal notes, written in Francis's voice.

Rules this file is held to. No em dashes anywhere. Every piece names the
received reading before taking it apart, because the point of the blog is that
the headline is usually describing something other than the asset. Judgements
are marked as judgements. Personal detail is only ever something documented on
his own site (the supplement shelf, the bloodwork, the training, the AI for
Business degree), and nothing about his life is invented to warm the prose up.
"""

STORIES = [

dict(
 slug="buying-the-standard",
 lead="", line1="Buying", conn="the", line2="Standard",
 sub=("FORTY PEOPLE IS THE WRONG", "NUMBER TO BE STARING AT"),
 party="Databricks / Tabular", value="~$2B", dated="June 2024",
 opening="Every write up of this deal reached for the same joke. Two billion dollars, roughly forty people, do the division, marvel at the price per head. I did the division too. Then I sat with it and decided the headcount is the least informative fact in the entire transaction, and that the people repeating it, myself included for about an hour, were solving the wrong problem.",
 sections=[
  ("What the acquihire framing misses",
   ["Tabular was founded by the engineers who created Apache Iceberg while they were at Netflix. Iceberg is an open table format, the unglamorous plumbing that decides how enormous piles of data get organised so different tools can read them. Call it a talent deal and you have described the receipt rather than the purchase.",
    "Here is the fact that reframed it for me. Databricks maintains Delta Lake, which was Iceberg's principal rival. So Databricks did not buy a capability it lacked, and it did not buy forty engineers it could have hired one at a time for a great deal less. It bought the other side of a format war, along with the specific people whose names are the reason anyone trusts that format."]),
  ("Why I think this is cheap, which is not the consensus",
   ["Two billion sounds absurd right up until you price the alternative. If the industry standardises on Iceberg and Databricks is outside it, then every enterprise data decision for the next decade begins with a format Databricks does not influence. That is not a competitive disadvantage, it is a gravity problem, and you do not fix gravity with a better product.",
    "My read is that this was never about revenue or engineers. It was about buying the right to stop competing against your own standard, and about being able to say that both formats now sit under one roof. Standards are not won by being better. They are won by becoming the default, and defaults have a price. I think this one was under it."]),
  ("The number nobody wants to look at",
   ["Databricks has confirmed publicly only that consideration exceeded one billion dollars. The two billion figure everyone quotes, mine included, is reporting.",
    "I find that gap interesting rather than sinister. A company that was delighted with a price tends to say the price. A company that would rather you discussed the strategy gives you a floor and lets the number find its own level. That is not evidence of anything. It is just a thing I notice, and I notice it often enough that it has become a tell."]),
  ("Where I would push back on myself",
   ["Iceberg is open, and the entire reason anyone trusts an open format is that no single commercial party steers it. The largest commercial party in the category now employs its creators.",
    "I have seen no evidence of anything going wrong and I do not think capture was the intent. But an open standard maintained by its biggest beneficiary is a structure that works exactly as long as everyone keeps behaving well, and I am not willing to call that a permanent condition."]),
  ("My call",
   ["Cheap if it ends the format war, expensive if the community reads it as a capture and routes around it. The checkable version of that question is whether Iceberg's contributor base stays genuinely broad over the next few years or quietly narrows to one company, and that is a thing you can go and look at rather than argue about."]),
 ],
 takeaway="They did not buy forty people. They bought the right to stop competing with their own standard.",
 srcs=["Databricks announcement, Data and AI Summit, 4 June 2024. Databricks has publicly confirmed consideration above one billion dollars; the approximately two billion figure is from subsequent reporting and is not company confirmed.",
       "Tabular founding team and the origin of Apache Iceberg at Netflix, per the companies' own materials."]),

dict(
 slug="bought-then-freed",
 lead="", line1="Bought", conn="then", line2="Freed",
 sub=("EVERYONE FILED THIS UNDER", "NVIDIA BUYING THE STACK"),
 party="NVIDIA / Run:ai", value="~$700M", dated="December 2024",
 opening="The tidy version of this deal is that NVIDIA is buying up the AI stack layer by layer, and Run:ai is one more brick in the wall. I understand why that framing is attractive. It is also the opposite of what happened, because within a day of owning the thing NVIDIA said it would release it as open source, which is a genuinely strange way to hoard something.",
 sections=[
  ("The sentence that would not parse",
   ["NVIDIA agreed to buy Run:ai in April 2024 and closed that December after review by the Department of Justice and the European Commission. Reported price is around seven hundred million dollars, which neither party confirmed. Then they gave it away.",
    "I reread that several times. Paying seven hundred million for something and immediately releasing it free is not a sentence that survives first contact with normal deal logic, and when a deal refuses to make sense on the obvious reading it usually means I am reading the wrong asset."]),
  ("What Run:ai actually is, which explains everything",
   ["Run:ai orchestrates GPU workloads across Kubernetes clusters. It decides which job gets which slice of which chip, and it lets a single physical GPU be shared rather than handed whole to one task. GPUs are the most expensive objects in the building and they spend an embarrassing amount of time idle, so orchestration is what turns a pile of hardware into a utility.",
    "That means orchestration sits one layer above the thing NVIDIA sells. It is a complement, not a product. And the correct move with a complement has been the same since Rockefeller was selling kerosene and giving away lamps: make it free, abundant and excellent, because every gram of friction you remove from the layer above lands as demand in the layer you own."]),
  ("So the accumulation story is backwards",
   ["Free orchestration that runs anywhere still has to schedule onto something. My read is that NVIDIA spent seven hundred million to make certain the scheduling layer never became a place a competitor could get a grip, and then removed any commercial reason for anyone to build an alternative.",
    "Against that balance sheet the price is close to a rounding error, and I think it is the cheapest defensive purchase on my list by a wide margin. Calling it accumulation misses that the strategic content is in the giving away, not the buying."]),
  ("The part that cuts against NVIDIA",
   ["Open source is not a one way door. Software that orchestrates GPUs generically is also software that makes it easier to orchestrate somebody else's GPUs.",
    "My concern is modest but real. The openness protecting the moat today lowers the switching cost tomorrow, and the parties most motivated to extend an open orchestrator are precisely the ones selling alternative silicon. I would not call that an error. I would call it a price NVIDIA looked at and decided it could afford."]),
  ("My call",
   ["A good trade and a clearer statement of strategy than anything in the announcement. What I would watch is not adoption, because adoption is guaranteed once a useful thing becomes free. It is who is contributing in three years, and what hardware those contributors happen to sell."]),
 ],
 takeaway="The strategy was not in the buying. It was in giving it away the moment they owned it.",
 srcs=["NVIDIA announcement of the agreement, April 2024; completion December 2024 following US and EU review.",
       "The approximately seven hundred million figure is from reporting and was not confirmed by either party; some accounts place it nearer eight hundred million."]),

dict(
 slug="the-missing-fifth",
 lead="The", line1="Missing", conn="", line2="Fifth",
 sub=("AN INDUSTRY DID THE ARITHMETIC", "AND NOBODY CHECKED THE STAKE"),
 party="Unilever / Gr&uuml;ns", value="~$1.2B", dated="June 2026",
 opening="I am not a neutral reader of this one and I would rather say so upfront. I take around fifteen things every day, I read the mechanism on each of them before they go in, and I get bloodwork drawn to check whether any of it does what it claims. So when Unilever completed its acquisition of Gr&uuml;ns on the first of June, my first thought was not the multiple. It was that another shelf in my own bathroom just changed owner.",
 sections=[
  ("The arithmetic everybody performed",
   ["Gr&uuml;ns was founded in 2023 by Chad Janis, sells a daily greens supplement in gummy form almost entirely by subscription, reached roughly three hundred million dollars of annual revenue in under four years, and was reported profitable inside about fourteen months. The deal came out at approximately one point two billion dollars, or seven hundred and sixty seven million euro.",
    "Then everyone, and I do mean nearly everyone, ran the same sum. One point two over three hundred, four times sales, sensible bolt on price, move along. I ran it as well. It took me an embarrassing amount of time to ask the obvious follow up question, which is four times sales of what exactly."]),
  ("Four fifths of a company is not a company",
   ["Trade reporting places that consideration against eighty percent of the shares rather than all of them. If that holds, the implied whole company value is nearer one and a half billion and the multiple is closer to five times than four.",
    "A full turn of revenue is not a rounding difference. It is the distance between a bolt on price and a growth price, and those imply completely different expectations about what has to happen next. What bothers me is not that the number moved. It is that an entire commentariat divided one figure by another without once asking what was in the numerator, and a press release ended up doing the analysis for the industry.",
    "I want to be careful, because I could not confirm the split in Unilever's own half year filing, which records the completion and says nothing at all about terms. So I am flagging it rather than banking it. But a reported figure that nobody has interrogated is not a fact, it is a rumour with a decimal point."]),
  ("What I think the unbought fifth is for",
   ["My read is that leaving twenty percent outstanding is not thrift. It is a retention device. Gr&uuml;ns is three years old and founder run, and the whole asset is a subscription machine somebody has been operating with unusual discipline. You do not buy that outright when what you actually need is for the operator to stay in the building.",
    "The deal term is doing more work than the headline, which is true of most deals and almost never written down."]),
  ("My concern, as somebody who buys this category",
   ["Here is what I actually care about, and it has nothing to do with Unilever's return. A greens gummy is a formulation, and formulations get revisited. Under a founder the reason to change a formula is usually efficacy. Under a large consumer owner with a cost line to manage, the reason can be margin.",
    "I have no evidence that anything of the kind has happened or is planned, and I want that stated plainly rather than buried. This is a concern, not a finding. But it is the first thing I will notice, because I read labels for fun and a quiet reformulation is exactly the sort of change that never gets an announcement."]),
  ("My call",
   ["A good price for Unilever if the subscription base holds, and the subscription base holds only as long as the product keeps doing what the people taking it believe it does. That is a much narrower dependency than four times revenue implies, and it is narrower still at five."]),
 ],
 takeaway="A reported number nobody has interrogated is not a fact. It is a rumour with a decimal point.",
 srcs=["Unilever Form 6-K, half year results to 30 June 2026, confirming completion in June 2026 and not stating terms.",
       "Consideration, revenue scale and the eighty percent stake are from trade reporting rather than the filing, and are treated here as reported rather than confirmed."]),

dict(
 slug="premium-without-profit",
 lead="", line1="Premium", conn="without", line2="Profit",
 sub=("A PREMIUM IS A RATIO TO", "A NUMBER SOMEBODY CHOSE"),
 party="Mars / Hotel Chocolat", value="&pound;534M", dated="November 2023",
 opening="A hundred and seventy percent premium is the kind of number that ends an argument before it starts. Half the coverage treated it as evidence Mars had lost its mind and the other half as a triumph for shareholders, and I think both readings are lazy for the same reason. A premium is not a measure of value. It is a ratio to a starting point, and somebody chose that starting point.",
 sections=[
  ("What you cannot do here",
   ["Mars offered five hundred and thirty four million pounds for Hotel Chocolat in November 2023, three hundred and seventy five pence a share in cash, closing that January. In the financial year to July 2023 Hotel Chocolat had moved from a pre tax profit of twenty one point seven million pounds to a loss of eight hundred thousand.",
    "So you cannot value this on earnings, because at the moment of the offer there effectively were not any. That is not a footnote, it is the whole puzzle. Whatever Mars was paying for was not a multiple of profit, and any take that starts from the premium is measuring from a price the market had already given up on."]),
  ("My explanation, which is about structure rather than chocolate",
   ["Look at what does exist. Hotel Chocolat was founded in 2004, sells through its own stores and its own website, and owns a hundred and forty acre cocoa estate and the Rabot Hotel in Saint Lucia. That is a company controlling its product from the tree to the till.",
    "My read is that Mars bought a structure it could not build. Mars is exceptional at manufacturing and at moving volume through other people's shelves. What it did not have is a premium brand with its own estate, its own retail, and a direct line to the person eating the thing. Vertical integration is slow, expensive and essentially impossible to assemble in pieces, so when you decide you want it you have to buy somebody who already did the twenty years. Framed that way the premium stopped looking irrational to me and started looking like the market had simply been pricing the wrong thing."]),
  ("What makes me hesitate",
   ["The quality that makes Hotel Chocolat worth a premium is that it is small enough to control end to end. Every move Mars makes to scale it, more stores, more countries, more volume pushed through a finite estate, is a step toward dissolving the thing that justified the price.",
    "My concern is not that Mars damages the brand on purpose. It is that the instinct making Mars excellent, push volume through distribution, is the precise instinct that unwinds a vertically integrated premium business. I have no evidence that is happening. It is the tension I would be watching, and I would watch it before I watched revenue."]),
  ("My call",
   ["Defensible, and considerably more interesting than the premium makes it sound. The metric I would track is not sales growth, it is the share of sales still moving through Hotel Chocolat's own channels. If that falls while total sales climb, Mars bought a brand and quietly let go of the reason it was worth buying."]),
 ],
 takeaway="You cannot pay a multiple of earnings for a company that stopped earning, so the premium is telling you what else was in the box.",
 srcs=["Mars offer announced 16 November 2023 at 375p per share; transaction completed 25 January 2024.",
       "Hotel Chocolat financial year to July 2023, pre tax result moving from a 21.7m profit to a 0.8m loss, per contemporaneous coverage of the company's results."]),

dict(
 slug="the-margin-gap",
 lead="The", line1="Margin", conn="", line2="Gap",
 sub=("FIFTY NINE IS THE NUMBER IN", "THE DECK, EIGHT IS THE BUSINESS"),
 party="Danone / Huel", value="~&pound;860M", dated="March 2026",
 opening="Direct to consumer brands love quoting gross margin, and I have started treating that as a small act of misdirection. Huel's is fifty nine percent, which sounds like a software company wearing an apron. Its adjusted EBITDA margin in the same year was about eight. Both numbers are true, only one gets said out loud, and the gap between them is the entire reason Danone bought the company.",
 sections=[
  ("Run the two lines yourself",
   ["I train for a half Ironman and I race HYROX, so complete nutrition is a category I watch as a person and not only as somebody reading filings. Danone announced the acquisition in March 2026 at around eight hundred and sixty million pounds and the CMA cleared it that August.",
    "In the financial year to 2024 Huel recorded two hundred and fourteen million pounds of revenue at a fifty nine percent gross margin, and eighteen point two million pounds of adjusted EBITDA. Revenue reached two hundred and fifty million the following year, up sixteen percent. Fifty nine percent of two hundred and fourteen is about a hundred and twenty six million of gross profit. EBITDA came in at eighteen. So roughly a hundred and eight million pounds, close to half of all revenue, leaves the building somewhere below the gross line."]),
  ("Which means the category is describing itself wrongly",
   ["In a subscription business selling direct, the overwhelming share of that hundred and eight million is the cost of finding the next customer. Huel is not expensive to make. Huel is expensive to sell.",
    "That is why I think the standard framing of this category is off. We talk about DTC brands as though the achievement is the product economics, and the fifty nine percent is genuinely good. But a fifty nine that arrives as an eight is not a product story, it is a customer acquisition story with a product attached, and the whole sector has been quoting the flattering half of that sentence for a decade."]),
  ("Why I think this synergy is real, which is rare for me",
   ["I am ordinarily sceptical of synergy arguments because they are the easiest slide in any deck and the hardest line to find afterwards. This one is different, and the difference is that the mechanism is concrete rather than cultural. Shelf space substitutes directly for paid acquisition. You are not hoping two organisations learn to collaborate. You are swapping a cost line for an asset the buyer already owns.",
    "My read is that Danone did not buy a food company at all. It bought a marketing bill it believes it can stop paying. And that gives a test requiring no model whatsoever: watch whether EBITDA margin climbs from eight toward the gross margin over three years. If it does, the thesis was right. If it has not moved, Danone bought revenue at a food multiple and inherited the advertising budget with it."]),
  ("My concern",
   ["Retail is not free, it is differently expensive, and a brand built on a subscription relationship does not always survive the move to a shelf where it sits beside eleven alternatives. Some of the loyalty in those numbers may be a function of the format rather than the formula.",
    "That is a hypothesis, not a finding. It is also why I would watch subscriber retention as closely as I watch the margin, because those two lines moving in opposite directions would tell you the trade went through and the asset did not."]),
  ("My call",
   ["The best articulated thesis on my list and the easiest to grade, which are related virtues. Fifty nine into eight is the whole deal. Either Danone closes that gap, or it did not need to own the company to find out."]),
 ],
 takeaway="Fifty nine percent arriving as eight is not a food business. It is customer acquisition with a product attached.",
 srcs=["Danone announcement March 2026; CMA clearance August 2026; consideration of approximately 860m from reporting.",
       "Huel FY2024 revenue, gross margin and adjusted EBITDA, and FY2025 revenue, per company figures reported in trade coverage."]),

dict(
 slug="two-versus-six",
 lead="", line1="Two", conn="versus", line2="Six",
 sub=("THE WELLNESS TRADE IS NOT", "ONE TRADE, AND HERE IS PROOF"),
 party="L Catterton / Good Culture", value="&gt;$500M", dated="January 2026",
 opening="People talk about the wellness trade as though it were a single thing you could be long or short. I have never quite believed that, and this year handed me the cleanest disproof I am likely to get. One sponsor, one calendar year, two health brands riding the same demand, priced at roughly two times revenue going in and roughly six times coming out.",
 sections=[
  ("The two numbers",
   ["In January 2026 L Catterton took a majority stake in Good Culture, the cottage cheese brand, at a reported value above five hundred million dollars. Good Culture did about a hundred million of revenue in 2023, close to double that in 2024, and was tracking near two hundred and fifty million in 2025. That is about two times sales. Semcap Food and Nutrition added a further fifty five million that February.",
    "In August the same firm sold Thorne to Procter and Gamble at a reported three point eight billion, against roughly six hundred and fifty million of forward revenue. About five point eight times."]),
  ("Two explanations I had to discard",
   ["My first instinct was growth, and it was wrong. Good Culture roughly doubled. That is not a business being marked down for stalling.",
    "My second was category, and that failed too. Both are things people put in their body deliberately, sold on a health claim, riding the same protein and longevity demand. If anything cottage cheese has had the louder cultural moment. So whatever is producing a four turn spread is not the thing the category label describes, which is exactly why I distrust the category label."]),
  ("What I think it actually is",
   ["My read is that the spread is copyability and very little else. Cottage cheese is a refrigerated commodity with a cold chain, a short shelf life, and a private label version on the same shelf at a lower price. A competitor can match the product. The brand is real and the execution is plainly excellent, but the moat is thin by construction and no amount of growth thickens it.",
    "Thorne's moat was a practitioner willing to say the name out loud to a patient who was frightened. You cannot private label that, and you cannot rebuild it once it has been spent. Four turns of revenue is what the market charges for that difference, and I find that a far more useful number than anything in the category commentary."]),
  ("Where I would push back on myself",
   ["I am aware I may be reading a sponsor's portfolio timing as a market judgement. L Catterton bought one asset and exited another, and exit timing has as much to do with fund cycles and a closed IPO window as with anything I am claiming about moats.",
    "I would rather name that objection than have it named for me. It is the strongest argument against my own read and I do not think it fully defeats it, because a fund cycle explains when you sell and not what somebody is willing to pay when you do."]),
  ("My call",
   ["Two was right for Good Culture and six was right for Thorne, and the distance between them is the most useful single fact I have learned about this aisle all year. If you want to know what a consumer health brand is worth, do not ask how fast it is growing. Ask whether somebody could make it for less, and whether anyone would notice."]),
 ],
 takeaway="Ask whether somebody could make it for less, and whether anyone would notice. That is the multiple.",
 srcs=["L Catterton majority investment in Good Culture announced January 2026, reported above 500m; Semcap Food and Nutrition investment of 55m, February 2026.",
       "Good Culture revenue scale from trade coverage. Thorne figures as set out in my separate note on that transaction."]),

dict(
 slug="owning-the-clock",
 lead="", line1="Owning", conn="the", line2="Clock",
 sub=("UNDISCLOSED IS NOT ABSENCE", "OF INFORMATION, IT IS SOME"),
 party="Infinite Epigenetics / Tally Health", value="Undisclosed", dated="April 2026",
 opening="When terms are not disclosed, the reflex is to assume the deal was small and move on. I have stopped doing that. Undisclosed is not an absence of information, it is a decision somebody made, and in this case I think the decision is more revealing than the number would have been. On the twenty ninth of April 2026, Infinite Epigenetics acquired Tally Health in an asset purchase, and I am the customer this one is about.",
 sections=[
  ("Read what actually changed hands",
   ["I get bloodwork drawn specifically to check whether the things I take are doing what they claim, which makes me precisely the person biological age testing is built for. So I read this announcement twice.",
    "Tally Health was co founded in 2023 by the Harvard geneticist David Sinclair and sells an epigenetic biological age test alongside a supplement line. The buyer also owns TruDiagnostic and states that it holds among the largest private datasets of adult DNA methylation. Tally continues as a standalone brand under Melanie Goldey. The obvious description is that a longevity company bought a longevity company, and that description is filed under the wrong heading. My read is that what was acquired is a methylation dataset and a competing clock, and the supplement line came along attached to it."]),
  ("A clock is not a measurement, and that distinction is everything",
   ["Biological age is not a measurement the way height is a measurement. It is a model. Somebody decides what counts as a year, which markers matter, and what the reference population looks like. Two clocks can read the same blood and disagree, and neither is lying.",
    "This is where I would push back on how the field talks about itself. A biological age result is presented to consumers with the confidence of a bathroom scale, and it is nothing of the kind. If you already hold the largest reference dataset and you then buy the most consumer visible rival clock, you have not added a product to a catalogue. You have consolidated the benchmark, and every longevity intervention that wants to claim it works eventually validates against somebody's clock. There is now one fewer somebody."]),
  ("My concern, and it is the personal one",
   ["Here is what actually bothers me as a customer rather than as an analyst. The company selling you the intervention now also owns the instrument grading whether the intervention worked.",
    "I want to be careful and precise. I have no evidence of manipulation, nothing in the announcement suggests any intent of the kind, and vertical structures like this are common in diagnostics and not improper in themselves. But it is a conflict existing by design rather than by accident, and if I am paying to find out whether my own stack does anything at all, I would prefer the scorekeeper and the vendor were different people. That preference is not a scandal. It is just a preference I am allowed to have with my own money."]),
  ("My call",
   ["The most strategically interesting deal on my list and the one carrying the least public information, which I do not think is a coincidence. What I will watch is narrow and checkable. Does Tally's test keep reporting on its own clock, or does it quietly migrate onto TruDiagnostic's? That single answer separates a portfolio addition from a benchmark consolidation, and I know which way I am leaning."]),
 ],
 takeaway="Whoever owns the clock decides what a year is worth, and there is now one fewer party deciding.",
 srcs=["Infinite Epigenetics announcement of the Tally Health asset purchase, 29 April 2026. Terms not disclosed by either party.",
       "Tally Health founding, leadership and product scope, and Infinite Epigenetics' ownership of TruDiagnostic, per the announcement."]),

]
