"""Deal notes, written in Francis's voice.

Voice rules this file is held to: no em dashes anywhere, the piece opens from
something he actually notices, every number is followed by what he makes of it,
and the close is a judgement that follows from the reasoning rather than a
summary. Personal detail is only used where it is documented on his own site
(the supplement shelf, the bloodwork, the training, the AI for Business degree).
Nothing about his life is invented to warm the prose up.
"""

STORIES = [

dict(
 slug="buying-the-standard",
 lead="", line1="Buying", conn="the", line2="Standard",
 sub=("DATABRICKS PAID AROUND TWO BILLION", "FOR ROUGHLY FORTY PEOPLE"),
 party="Databricks / Tabular", value="~$2B", dated="June 2024",
 opening="I study AI for business, so my instinct with a deal like this is to look for the model, the training run, the thing that sounds like the future. Databricks bought Tabular in June 2024 and there is no model in it at all. Roughly forty people. A file format. Reporting put the price near two billion dollars, and Databricks itself has only ever confirmed that it cleared one billion, which is its own small tell about how they would like this discussed.",
 sections=[
  ("What forty people were actually holding",
   ["Tabular was founded by the engineers who created Apache Iceberg while they were at Netflix. Iceberg is an open table format, which is the boring layer of plumbing that decides how enormous piles of data get organised so that different tools can read them.",
    "Here is the part that made me sit up. Databricks maintains Delta Lake, which was Iceberg's main rival. So Databricks did not buy a company that complemented its product. It bought the other side of a format war, and it bought the specific people whose names give that format its legitimacy."]),
  ("Why I think the price makes sense",
   ["Two billion for forty people reads insane until you price the alternative. If the industry standardises on Iceberg and Databricks is on the outside of it, every enterprise data decision for the next decade starts with a format Databricks does not control. That is not a product problem, it is a gravity problem.",
    "My read is that they were not buying revenue and they were not buying engineers. They were buying the right to stop competing with themselves, and the ability to say that both formats now sit under one roof. Standards do not get won by being better. They get won by being the default, and defaults are bought."]),
  ("My concern",
   ["Iceberg is open, and the whole reason anyone trusts an open format is that no single commercial party is steering it. Now the largest commercial party in the category employs the people who created it.",
    "I do not think that was the intent and I have seen no evidence of anything going wrong. But governance is the thing I would watch, because an open standard maintained by its biggest beneficiary is a structure that only works while everyone keeps behaving well."]),
  ("My call",
   ["Cheap, if it ends the format war. Expensive, if the community reads the acquisition as a capture and routes around it. The measurable version of that question is whether Iceberg's contributor base stays broad over the next few years, or quietly narrows to one company."]),
 ],
 takeaway="They did not buy a product. They bought the right to stop competing with their own standard.",
 srcs=["Databricks announcement, Data and AI Summit, 4 June 2024. Databricks has publicly confirmed consideration above one billion dollars; the roughly two billion figure comes from subsequent reporting and has not been confirmed by the company.",
       "Tabular founding team and Apache Iceberg origin at Netflix, per the companies' own materials."]),

dict(
 slug="bought-then-freed",
 lead="", line1="Bought", conn="then", line2="Freed",
 sub=("SEVEN HUNDRED MILLION DOLLARS", "AND THEN THEY GAVE IT AWAY"),
 party="NVIDIA / Run:ai", value="~$700M", dated="December 2024",
 opening="This is the deal on my list that confused me longest. NVIDIA agreed to buy Run:ai in April 2024 and closed it that December after review by the Department of Justice and the European Commission. Reported price is around seven hundred million dollars, which neither side confirmed. Then, on closing, NVIDIA said it would release the software as open source. I kept rereading that, because paying seven hundred million dollars for something and immediately giving it away is not a sentence that parses on first contact.",
 sections=[
  ("What Run:ai does",
   ["Run:ai was an Israeli company whose software orchestrates GPU workloads across Kubernetes clusters. In plain terms, it decides which job gets which slice of which chip, and it lets one physical GPU be shared out rather than handed whole to a single task.",
    "That matters because GPUs are the most expensive things in the building and they spend a shocking amount of time idle. Orchestration is what turns a pile of hardware into a utility."]),
  ("Why giving it away is the whole point",
   ["Orchestration sits one layer above the thing NVIDIA actually sells. It is a complement, not a product, and the strategic move with a complement has always been to make it free, abundant and excellent, because every dollar of friction you remove from the layer above lands as demand in the layer you own.",
    "Free orchestration that runs anywhere still has to schedule onto something. My read is that NVIDIA spent seven hundred million dollars to make sure the scheduling layer was never a place where a competitor could get a foothold, and then removed any reason for anyone to build an alternative. On a balance sheet that size it is close to a rounding error, and it is the cheapest defensive purchase on my list."]),
  ("The part that cuts both ways",
   ["Open source is not a one way door. Software that orchestrates GPUs generically is also software that makes it easier to orchestrate somebody else's GPUs.",
    "My concern is small but real: the same openness that protects the moat today lowers the switching cost tomorrow, and the people most motivated to extend an open orchestrator are exactly the ones selling alternative silicon. I would not call that a mistake. I would call it the price NVIDIA decided was worth paying."]),
  ("My call",
   ["A good trade, and a clearer statement of strategy than anything in the press release. The thing I would watch is not adoption, because adoption is guaranteed when something useful becomes free. It is who is contributing to it in three years, and what hardware they happen to sell."]),
 ],
 takeaway="You buy the layer above your moat so that nobody else can, and then you make it free so nobody needs to.",
 srcs=["NVIDIA announcement of the agreement, April 2024; completion December 2024 following US and EU review.",
       "Price of approximately seven hundred million dollars is from reporting and was not confirmed by either party; some accounts place it nearer eight hundred million."]),

dict(
 slug="the-missing-fifth",
 lead="The", line1="Missing", conn="", line2="Fifth",
 sub=("EVERYONE QUOTED THE MULTIPLE", "NOBODY CHECKED THE STAKE"),
 party="Unilever / Gr&uuml;ns", value="~$1.2B", dated="June 2026",
 opening="I am not a neutral reader of this one. I take around fifteen things every day, I read the mechanism on each of them before they go in, and I get bloodwork drawn to check whether any of it is doing what it claims. So when Unilever completed its acquisition of Gr&uuml;ns on the first of June, my first thought was not about the multiple. It was that another shelf in my own category just changed owner.",
 sections=[
  ("The number everyone repeated",
   ["Gr&uuml;ns was founded in 2023 by Chad Janis, sells a daily greens supplement in gummy form almost entirely by subscription, reached roughly three hundred million dollars of annual revenue in under four years, and was reported profitable within about fourteen months. The deal came out at approximately one point two billion dollars, or seven hundred and sixty seven million euro.",
    "Almost every write up then did the same arithmetic. One point two billion over three hundred million, so four times sales, so a sensible bolt on price. I did it too, and then I went looking for the share count, which is where it gets interesting."]),
  ("Four fifths is not the whole thing",
   ["Trade reporting places that consideration against eighty percent of the shares rather than all of them. If that is right, the implied whole company value is closer to one and a half billion and the multiple is nearer five times, not four.",
    "A full turn of revenue is not a detail. It is the difference between a bolt on price and a growth price, and those two numbers imply completely different expectations about what happens next. I want to be careful here, because I could not confirm the split in Unilever's own half year filing, which records the completion and says nothing about terms. So I am flagging it rather than banking it."]),
  ("What I think the unpurchased fifth is for",
   ["My read is that leaving twenty percent outstanding is not thrift. It is a retention device. Gr&uuml;ns is three years old and founder run, and the entire asset is a subscription machine that somebody has been operating with unusual discipline. You do not buy that outright if what you actually need is for the operator to stay.",
    "The deal term is doing more work than the headline, which is generally true and almost never written down."]),
  ("My concern as somebody who buys this category",
   ["Here is what I actually care about. A greens gummy is a formulation, and formulations get revisited. Under a founder, the reason to change the formula is usually efficacy. Under a large consumer owner with a cost line to manage, the reason to change it can be margin.",
    "I have no evidence that anything like that has happened or is planned, and I want to be clear that this is a concern rather than a finding. But it is the thing I will notice first, because I read labels for a living and for fun, and a quiet reformulation is exactly the kind of change that never makes an announcement."]),
  ("My call",
   ["A good price for Unilever if the subscription base holds, and the subscription base holds as long as the product keeps doing what the people taking it think it does. That is a narrower dependency than four times revenue suggests."]),
 ],
 takeaway="The multiple everyone quoted was priced against four fifths of a company.",
 srcs=["Unilever Form 6-K, half year results to 30 June 2026, confirming completion in June 2026 and not stating terms.",
       "Consideration, revenue scale and the eighty percent stake are from trade reporting rather than the filing, and are treated here as reported rather than confirmed."]),

dict(
 slug="premium-without-profit",
 lead="", line1="Premium", conn="without", line2="Profit",
 sub=("A HUNDRED AND SEVENTY PERCENT", "FOR A COMPANY LOSING MONEY"),
 party="Mars / Hotel Chocolat", value="&pound;534M", dated="November 2023",
 opening="I collect deals where the price refuses to make sense on the obvious metric, and this is one of my favourites. Mars offered five hundred and thirty four million pounds for Hotel Chocolat in November 2023, three hundred and seventy five pence a share in cash, which was a premium of roughly a hundred and seventy percent to the previous close. In the financial year to July 2023 Hotel Chocolat had gone from a pre tax profit of twenty one point seven million pounds to a loss of eight hundred thousand.",
 sections=[
  ("Start with what you cannot do here",
   ["You cannot value this on earnings, because at the moment of the offer there effectively were not any. Whatever Mars was paying for, it was not a multiple of profit, and that alone makes the deal more interesting than most of the list.",
    "So the question becomes what does exist. Hotel Chocolat was founded in 2004, sells through its own stores and its own website, and owns a hundred and forty acre cocoa estate and the Rabot Hotel in Saint Lucia. That is a company that controls its product from the tree to the till."]),
  ("My explanation",
   ["My read is that Mars bought a structure it could not build. Mars is extraordinary at manufacturing and distribution, which means it is extraordinary at selling chocolate through other people's shelves. What it does not have is a premium brand with its own estate, its own retail, and a direct relationship with the person eating the thing.",
    "Vertical integration is slow and expensive to assemble and nearly impossible to acquire in pieces. When you decide you want it, you have to buy somebody who already did the twenty years of work. That is what a hundred and seventy percent premium is actually pricing, and once I framed it that way the number stopped looking irrational to me."]),
  ("What makes me hesitate",
   ["The thing that makes Hotel Chocolat worth a premium is that it is small enough to control end to end. Every step Mars takes to scale it, more stores, more countries, more volume through the estate, is a step toward the model that made the premium worth paying evaporating.",
    "My concern is not that Mars will damage the brand deliberately. It is that the instinct which makes Mars excellent, push volume through distribution, is precisely the instinct that dissolves a vertically integrated premium business. I have no evidence of that happening. It is simply the tension I would be watching."]),
  ("My call",
   ["Defensible, and more interesting than the premium makes it look. The number I would track is not revenue growth, it is the share of sales still going through Hotel Chocolat's own channels. If that falls while total sales rise, Mars bought a brand and let go of the reason it was worth buying."]),
 ],
 takeaway="You cannot pay a multiple of earnings for a company that has stopped earning, so the premium is telling you what else was in the box.",
 srcs=["Mars offer announced 16 November 2023 at 375p per share; transaction completed 25 January 2024.",
       "Hotel Chocolat financial year to July 2023, pre tax result moving from a 21.7m profit to a 0.8m loss, per contemporaneous coverage of the company's results."]),

dict(
 slug="the-margin-gap",
 lead="The", line1="Margin", conn="", line2="Gap",
 sub=("FIFTY NINE PERCENT AT THE TOP", "EIGHT PERCENT BY THE BOTTOM"),
 party="Danone / Huel", value="~&pound;860M", dated="March 2026",
 opening="I train for a half Ironman and I race HYROX, so complete nutrition is a category I pay attention to as a person and not only as somebody reading filings. Danone announced its acquisition of Huel in March 2026 at around eight hundred and sixty million pounds and the CMA cleared it that August. The number that stopped me was not the price. It was the gap between two lines on Huel's own income statement.",
 sections=[
  ("Run the two lines",
   ["In the financial year to 2024 Huel recorded two hundred and fourteen million pounds of revenue at a fifty nine percent gross margin, and eighteen point two million pounds of adjusted EBITDA. Revenue reached two hundred and fifty million the following year, up sixteen percent.",
    "Fifty nine percent of two hundred and fourteen million is about a hundred and twenty six million of gross profit. EBITDA came in at eighteen. So roughly a hundred and eight million pounds, close to half of all revenue, goes out somewhere below the gross line. In a direct to consumer subscription business, the overwhelming majority of that is the cost of finding the next customer."]),
  ("What that tells me the business actually is",
   ["Huel is not expensive to make. Huel is expensive to sell. A fifty nine percent gross margin says the product economics are genuinely good, and an eight percent EBITDA margin says almost all of that good is being spent on acquisition.",
    "My read is that Danone did not buy a food company. It bought a marketing bill it believes it can stop paying, because the thing Danone owns in abundance is the one thing Huel has been renting at enormous cost, which is access to the customer."]),
  ("Why I think this synergy is real",
   ["I am usually sceptical of synergy arguments because they are the easiest slide in the deck to write and the hardest line to find afterwards. This one is different, because the mechanism is concrete rather than cultural. Shelf space substitutes directly for paid acquisition. You are not hoping two teams collaborate. You are swapping one cost line for an asset you already own.",
    "That gives a test that needs no model. Watch whether EBITDA margin climbs from eight toward the gross margin over the next three years. If it does, the thesis was right. If it has not moved, Danone bought revenue at a food multiple and inherited the advertising budget along with it."]),
  ("My concern",
   ["Retail is not free, it is just differently expensive, and a brand built on a subscription relationship does not always survive the move to a shelf where it sits beside eleven alternatives. The loyalty that made the DTC numbers work may be partly a function of the DTC format itself.",
    "That is a hypothesis rather than a finding. But it is why I would watch subscriber retention as closely as I watch the margin."]),
  ("My call",
   ["The best articulated thesis on my list, and the easiest to grade. Fifty nine into eight is the whole deal, and either Danone closes that gap or it did not need to own the company to find out."]),
 ],
 takeaway="Fifty nine percent at the gross line arriving as eight at EBITDA is not a food business, it is a customer acquisition business.",
 srcs=["Danone announcement March 2026; CMA clearance August 2026; consideration of approximately 860m from reporting.",
       "Huel FY2024 revenue, gross margin and adjusted EBITDA, and FY2025 revenue, per company figures reported in trade coverage."]),

dict(
 slug="two-versus-six",
 lead="", line1="Two", conn="versus", line2="Six",
 sub=("ONE SPONSOR, ONE YEAR", "TWO TIMES IN, SIX TIMES OUT"),
 party="L Catterton / Good Culture", value="&gt;$500M", dated="January 2026",
 opening="I noticed this one because I had already spent weeks inside the other half of it. In January 2026 L Catterton took a majority stake in Good Culture, the cottage cheese brand, at a reported value above five hundred million dollars. In August of the same year, the same firm sold Thorne to Procter and Gamble at a reported three point eight billion. One sponsor, one calendar year, buying at roughly two times revenue and selling at roughly six.",
 sections=[
  ("The two numbers",
   ["Good Culture did about a hundred million dollars of revenue in 2023, close to double that in 2024, and was tracking near two hundred and fifty million in 2025. Above five hundred million on that base is about two times sales. Semcap Food and Nutrition put a further fifty five million in that February.",
    "Thorne did over five hundred million in 2025 against roughly six hundred and fifty million tracked for 2026, which puts three point eight billion at around five point eight times forward revenue."]),
  ("What the spread is not",
   ["My first instinct was that the gap is growth, and that instinct was wrong. Good Culture roughly doubled. That is not a slow business and it is not being priced like one because it is stalling.",
    "It is also not category. Both of these are things people put in their body on purpose, sold on a health claim, riding the same protein and wellness demand. If anything, cottage cheese has had the louder cultural moment of the two."]),
  ("What I think it is",
   ["My read is that the spread is copyability, and almost nothing else. Cottage cheese is a refrigerated commodity. It has a cold chain, a short shelf life, and a private label version sitting on the same shelf at a lower price. A competitor can match the product. The brand is real and the execution is clearly excellent, but the moat is thin by construction.",
    "Thorne's moat was a practitioner willing to say the name out loud to a patient who was frightened. You cannot private label that and you cannot rebuild it once it is spent. Four turns of revenue is what the market charges for the difference."]),
  ("Why I care about this one",
   ["This is the clearest natural experiment I have found for something I already thought. Same buyer, same year, same broad thesis about health, and the only variable that really moves is whether somebody with credentials is prepared to attach their reputation to the product.",
    "My concern, and it is a genuine one, is that I may be reading a sponsor's portfolio timing as a market judgement. L Catterton bought one asset and exited another, and the exit timing has as much to do with fund cycles and a closed IPO window as with anything I am claiming. I would rather name that than have it named for me."]),
  ("My call",
   ["Two is the right number for Good Culture and six was the right number for Thorne, and the distance between them is the most useful single fact I have learned about this aisle all year. If you want to know what a consumer health brand is worth, do not ask how fast it is growing. Ask whether somebody could make it for less and whether anyone would notice."]),
 ],
 takeaway="The multiple is answering one question. Can somebody make this for less, and would anyone notice.",
 srcs=["L Catterton majority investment in Good Culture announced January 2026, reported above 500m; Semcap Food and Nutrition investment of 55m, February 2026.",
       "Good Culture revenue scale from trade coverage. Thorne figures as set out in my separate note on that transaction."]),

dict(
 slug="owning-the-clock",
 lead="", line1="Owning", conn="the", line2="Clock",
 sub=("NO PRICE WAS DISCLOSED", "AND THE ASSET IS A DATASET"),
 party="Infinite Epigenetics / Tally Health", value="Undisclosed", dated="April 2026",
 opening="This is the one on my list that I keep thinking about after I close the tab, and it is because I am the customer. I get bloodwork drawn specifically to check whether the things I take are doing what they claim, which means I am exactly the person biological age testing is built for. On the twenty ninth of April 2026, Infinite Epigenetics acquired Tally Health in an asset purchase. Terms were not disclosed by either party, and I am not going to invent a multiple for a price nobody published.",
 sections=[
  ("Read what actually changed hands",
   ["Tally Health was co founded in 2023 by the Harvard geneticist David Sinclair and sells an epigenetic biological age test alongside a line of supplements. The buyer also owns TruDiagnostic and states that it holds among the largest private datasets of adult DNA methylation. Tally continues as a standalone consumer brand under Melanie Goldey.",
    "So the obvious description is that a longevity company bought a longevity company. My read is that what was really acquired is a methylation dataset and a competing clock, and the supplement line came along attached."]),
  ("Why a clock is not a measurement",
   ["Biological age is not a measurement in the way height is a measurement. It is a model. Somebody has to decide what counts as a year, which markers matter, and what the reference population looks like. Two clocks can look at the same blood and disagree, and neither of them is lying.",
    "If you already hold the largest reference dataset and you then buy the most consumer visible rival clock, you have not added a product to a catalogue. You have consolidated the benchmark. Every longevity intervention that wants to claim it works eventually has to validate against somebody's clock, and now there is one fewer somebody."]),
  ("My concern, and it is the personal one",
   ["Here is what actually bothers me as a customer rather than as an analyst. The company that sells you the intervention now also owns the instrument that grades whether the intervention worked.",
    "I want to be careful and precise about this. I have no evidence of any manipulation, and nothing in the announcement suggests any intent of that kind. The structure is common in diagnostics and it is not inherently improper. But it is a conflict that exists by design rather than by accident, and if I am paying to find out whether my own stack does anything, I would like the scorekeeper and the vendor to be different people."]),
  ("My call",
   ["The most strategically interesting deal on my list and the one with the least public information, which is not a coincidence. The thing I will watch is narrow and checkable. Does Tally's test keep reporting on its own clock, or does it quietly migrate onto TruDiagnostic's? That single answer tells you whether this was a portfolio addition or a benchmark consolidation, and I know which way I am leaning."]),
 ],
 takeaway="Whoever owns the clock decides what a year is worth, and right now that is one fewer party than it was.",
 srcs=["Infinite Epigenetics announcement of the Tally Health asset purchase, 29 April 2026. Terms not disclosed by either party.",
       "Tally Health founding, leadership and product scope, and Infinite Epigenetics' ownership of TruDiagnostic, per the announcement."]),

]
